/******* CANVAS VALUES ********/
var MAX_X = 520; 
var MIN_X = 0; 
var MAX_Y = 565;
var MIN_Y = 0; 

var TRANSPARENT_LEFT_X = 0;
var TRANSPARENT_RIGHT_X = 20;
var TRANSPARENT_TOTAL_X = TRANSPARENT_LEFT_X + TRANSPARENT_RIGHT_X;
var TRANSPARENT_TOP_Y = 0;
var TRANSPARENT_FLOOR_Y = 65;
var TRANSPARENT_TOTAL_Y = TRANSPARENT_TOP_Y + TRANSPARENT_FLOOR_Y;

var VECTOR_INFO_MAX_DELAY = 40;
var VECTOR_INFO_MIN_DELAY = 20;

var OBJECT_X_DOWNCORNER_INIT_VALUE = 210;

var VECTOR_STROKE_SIZE = '6';

/******* SLIDER VALUES ********/
var DEFAULT_OBJ_MASS = 350;
var MIN_OBJ_MASS_SLIDER = 200;
var MAX_OBJ_MASS_SLIDER = 500;

var DEFAULT_PITCH = 20;
var MIN_PITCH_SLIDER = 5;
var MAX_PITCH_SLIDER = 45;

var DEFAULT_FRICTION_COEFFICIENT = 0.70;
var MIN_FRICTION_COEFFICIENT_SLIDER = 0.01;
var MAX_FRICTION_COEFFICIENT_SLIDER = 1.00;

var DEFAULT_EXTRA_FORCE = 0;
var MIN_EXTRA_FORCE_SLIDER = -4000;
var MAX_EXTRA_FORCE_SLIDER = 4000;

/******* PHISICS CONSTANTS ********/
var G_FORCE = 9.81;
var PI = 3.14;
var MAX_OBJ_WEIGHT = MAX_OBJ_MASS_SLIDER * G_FORCE;

/******* ANIMATION ********/
var AMINATION_GODOWN_X_PIXELS = 100;
var AMINATION_GOUP_X_PIXELS = 100;
var ANIMATION_DEFAULT_TIME = 1000;

/******* VECTOR ********/
var MIN_VECTOR_SIZE = 18;

/******* VECTOR ********/
var OBJECT_WIDTH = 100;
var OBJECT_HEIGHT = 60;