/******* CANVAS VALUES ********/
var MAX_X = 400; 
var MIN_X = 0; 
var MAX_Y = 510;
var MIN_Y = 0; 
var TRANSPARENT_TOP_Y = 30;
var TRANSPARENT_FLOOR_Y = 80;
var TRANSPARENT_TOTAL_Y = TRANSPARENT_TOP_Y + TRANSPARENT_FLOOR_Y;

var OBJECT_CENTER_X = (MAX_X - MIN_X) / 2;
var OBJECT_CENTER_Y = (MAX_Y - MIN_Y - TRANSPARENT_FLOOR_Y) / 2 + TRANSPARENT_TOP_Y / 2;

var VECTOR_INFO_X_DELAY = 40;

/******* SLIDER VALUES ********/
var DEFAULT_OBJ_MASS = 500;
var MIN_OBJ_MASS_SLIDER = 100;
var MAX_OBJ_MASS_SLIDER = 1000;

var DEFAULT_OBJ_VOLUME = 0.75;
var MIN_OBJ_VOLUME_SLIDER = 0.1;
var MAX_OBJ_VOLUME_SLIDER = 1.0;

var DEFAULT_FLUID_DENSITY = 1000;
var MIN_FLUID_DENSITY_SLIDER = 100;
var MAX_FLUID_DENSITY_SLIDER = 1500;

/******* PHISICS CONSTANTS ********/
var G_FORCE = 9.81;
var PI = 3.14;
var MAX_OBJ_WEIGHT = MAX_OBJ_MASS_SLIDER * G_FORCE;

/******* ANIMATION ********/
var ANIMATION_LINEAR = 'linear';
var ANIMATION_BOUNCE = 'bounce';
var ANIMATION_BACKOUT = 'backOut';
var ANIMATION_ELASTIC = 'elastic';

var ANIMATION_DEFAULT_TIME = 1000;

/******* VECTOR ********/
var MIN_VECTOR_SIZE = 20;